### PR TITLE
Fixed weird sound bug

### PR DESCRIPTION
**Pull request by rpcope1**

### CODE REVIEW

**Comment by youngkingtut** [comment]
I also encountered that error, do you know why we were seeing that?

**Comment by rpcope1** [comment]
My guess is that if it works on Charley's computer, then the API for Pygame has changed at some point for that call to Sound() to make a non-keyword arg into a keyword arg. _Assuming that the only keyword argument is file=_ the safest thing to do is just punt the filename as a regular argument.

**Comment by cparker1** [comment]
http://i.imgur.com/oGuIWFU.gifv

**Comment by rpcope1** [comment]
Are you going to merge the fix here?

**Pull request merged**
